### ISSUE TITLE
Plugin crash at server launch - Spigot 1.9.4

### ISSUE THREAD

**Issue by Maxcension** [AlessioDP/LastLoginAPI#3]
Hello!
The plugin crash at launch on my 1.9.4 Spigot server.
There is the crash message:
`[00:16:32] [Server thread/ERROR]: Could not load 'plugins/LastLoginAPI-1.3.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[spigotmc-1.9.4-R0.1.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigotmc-1.9.4-R0.1.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugins(CraftServer.java:297) [spigotmc-1.9.4-R0.1.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:200) [spigotmc-1.9.4-R0.1.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigotmc-1.9.4-R0.1.jar:git-Spigot-798f32d-0cd0397]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.util.zip.ZipException: invalid CEN header (bad signature)
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_192]
	at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_192]
	at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_192]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_192]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_192]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[spigotmc-1.9.4-R0.1.jar:git-Spigot-798f32d-0cd0397]
	... 5 more
[00:16:32] [Server thread/INFO]: Set PluginClassLoader as parallel capable`
The entire log (but i don't think there is anything revelant on it: https://pastebin.com/k5Qyv2Fs

I tried to find the plugin.yml file but i didn't find it, and there is no folder created in the /plugins/ with configuration files.

Have a nice day and thanks!

**Comment by AlessioDP** [comment]
The plugin.yml must exists inside the .jar. Try to redownload the file from spigotmc.org :wink:

**Comment by Maxcension** [comment]
> The plugin.yml must exists inside the .jar. Try to redownload the file from spigotmc.org 😉

Yeah it exists inside the .jar sorry, i was speaking on the /plugins/ folder haha!

**Comment by AlessioDP** [comment]
Test on my server and it works, be sure you are downloading correctly and its not corrupted.
The MD5 hash is: A1B028270629041F7383418881636890

**Comment by Maxcension** [comment]
> Test on my server and it works, be sure you are downloading correctly and its not corrupted.
> The MD5 hash is: A1B028270629041F7383418881636890

Ok so it seems that WinSCP corrupt the file when transfert it through FTP (everytime i tried to transfert it and redownload it with WinSCP, the MD5 was different).
When using an online FTP client, the plugin can load without a problem.
Thanks a lot for your help!
