### ISSUE TITLE
LastLoginAPI does not enable on startup - Mohist 1.12.2 #208

### ISSUE THREAD

**Issue by Agrrox** [AlessioDP/LastLoginAPI#31]
**Description of issue :**
LastLoginAPI does not enable on startup.

**Minecraft Version :** 1.12.2

**Mohist Version :** #208

**Operating System :** Linux - Ubuntu 4.15.0-112-generic (web hosting service)

<details> 
<summary>Logs :</summary>
error starts on line 6174

[2021-05-07-1 3.log](https://github.com/AlessioDP/LastLoginAPI/files/6444511/2021-05-07-1.3.log)
</details>

<details> 
<summary>Mod list :</summary>

```
Name : Minecraft
ModID : minecraft
Version : 1.12.2
---------
Name : Minecraft Coder Pack
ModID : mcp
Version : 9.42
---------
Name : Mohist
ModID : mohist
Version : 1.12.2-208
---------
Name : Forge Mod Loader
ModID : FML
Version : 8.0.99.99
---------
Name : Minecraft Forge
ModID : forge
Version : 14.23.5.2854
---------
Name : Cubic Chunks Coremod
ModID : cubicchunkscore
Version : 1.12.2-0.0.1185.0-SNAPSHOT
---------
Name : Aroma1997Core
ModID : aroma1997core
Version : 2.0.0.2.b167
---------
Name : AromaBackup
ModID : aromabackup
Version : 3.0.0.0.b135
---------
Name : AromaBackuprecovery
ModID : aromabackuprecovery
Version : 3.0.0.0.b135
---------
Name : Banner mod
ModID : bannermod
Version : 1.1.0
---------
Name : Cubic Chunks Pregenerator
ModID : ccpregen
Version : 0.0.21
---------
Name : CubicChunks
ModID : cubicchunks
Version : 1.12.2-0.0.1185.0-SNAPSHOT
---------
Name : CubicGen
ModID : cubicgen
Version : 1.12.2-0.0.145.0-SNAPSHOT
---------
Name : RealCoords
ModID : realcoords
Version : 0.0.6
---------
Name : TerraPlusPlus
ModID : terraplusplus
Version : 1.1.0.582-1.12.2
---------
Name : Terramap
ModID : terramap
Version : 1.0.0-beta7.8_1.12.2
---------
Name : WorldEdit
ModID : worldedit
Version : 6.1.11-SNAPSHOT
---------
```
</details>
<details> 
<summary>Plugin list :</summary>

```
Name : LuckPerms
Version : 5.3.0
---------
Name : WorldEdit
Version : 6.1.9;caf0ad9
---------
Name : Sledgehammer
Version : 0.4.2
---------
Name : BannerText
Version : 1.12.2-1
---------
Name : PlaceholderAPI
Version : 2.10.9
---------
Name : UltimateHeads
Version : 1.8
---------
Name : TabTPS
Version : 1.3.5
---------
Name : WorldGuard
Version : 6.2.2-SNAPSHOT;8eeab68
---------
Name : ProtocolLib
Version : 4.5.1
---------
Name : SchematicBrush
Version : 0.5.2-20
---------
Name : BungeeGuard
Version : 1.0-SNAPSHOT
---------
Name : VoxelSniper
Version : 5.171.0-CC_COMPAT-SNAPSHOT
---------
Name : BetterBrushes
Version : 1.0.0.140406
---------
Name : Vault
Version : 1.6.7-b${env.TRAVIS_BUILD_NUMBER}
---------
Name : RelativeCoordCalculator
Version : 0.5
---------
Name : F3NPerm
Version : 2.5
---------
Name : VentureChat
Version : 2.22.8
---------
Name : Skript
Version : 2.5.3
---------
Name : LastLoginAPI
Version : 1.5.1
---------
Name : Essentials
Version : 2.18.2.0
---------
Name : BKCommonLib
Version : 1.16.5-v3-SNAPSHOT
---------
Name : AnnouncerPlus
Version : 1.2.3
---------
Name : AdvancedBan
Version : 2.3.0
---------
Name : LightCleaner
Version : 1.16.5-v1
---------
Name : ExtraContexts
Version : 2.0-SNAPSHOT
---------
Name : HeadDatabase
Version : 4.13.5
---------
Name : HolographicDisplays
Version : 2.4.6
---------
Name : CommandSigns
Version : 1.6.7
---------
Name : BannerMaker
Version : 1.9.0
---------
Name : DeluxeMenus
Version : 1.13.3-Release
---------
Name : ItemJoin
Version : 5.2.1-RELEASE-b678
---------
Name : EssentialsSpawn
Version : 2.18.2.0
---------
Name : WorldGuardExtraFlags
Version : 4.1.4
---------
Name : HolographicExtension
Version : 1.10.9
---------
Name : TouchscreenHolograms
Version : 1.4.2
---------
```
</details>

**Comment by AlessioDP** [comment]
I tested a clean Mohist #213, be sure to delete plugins/LastLoginAPI/lib folder and restart the server.

It should work with Java 8-15.

**Comment by Agrrox** [comment]
Seems like it loaded and its working but with some warnings, is that ok?
<details><summary>logs</summary>

```
[01:10:02 INFO]: [LastLoginAPI] Initializing LastLoginAPI v1.5.1
[01:10:02 WARN]: [LastLoginAPI] The configuration key 'storage.storage-settings.remote-sql.address' in 'config.yml' was not found, configuration outdated?
[01:10:02 WARN]: [LastLoginAPI] The configuration key 'storage.storage-settings.remote-sql.port' in 'config.yml' was not found, configuration outdated?
[01:10:02 WARN]: [LastLoginAPI] The configuration key 'storage.storage-settings.remote-sql.database' in 'config.yml' was not found, configuration outdated?
[01:10:02 WARN]: [LastLoginAPI] The configuration key 'storage.storage-settings.remote-sql.username' in 'config.yml' was not found, configuration outdated?
[01:10:02 WARN]: [LastLoginAPI] The configuration key 'storage.storage-settings.remote-sql.password' in 'config.yml' was not found, configuration outdated?
[01:10:02 WARN]: [LastLoginAPI] The configuration key 'storage.storage-settings.remote-sql.pool-size' in 'config.yml' was not found, configuration outdated?
[01:10:02 WARN]: [LastLoginAPI] The configuration key 'storage.storage-settings.remote-sql.connection-lifetime' in 'config.yml' was not found, configuration outdated?
[01:10:02 WARN]: [LastLoginAPI] The configuration key 'storage.storage-settings.remote-sql.use-ssl' in 'config.yml' was not found, configuration outdated?
[01:10:02 WARN]: [LastLoginAPI] The configuration key 'storage.storage-settings.remote-sql.charset' in 'config.yml' was not found, configuration outdated?
[01:10:02 WARN]: [LastLoginAPI] The file config.yml is outdated!
[01:10:02 INFO]: [LastLoginAPI] Downloaded library https://repo1.maven.org/maven2/org/reflections/reflections/0.9.12/reflections-0.9.12.jar
[01:10:02 INFO]: [LastLoginAPI] Downloaded library https://repo1.maven.org/maven2/org/ow2/asm/asm-commons/7.1/asm-commons-7.1.jar
[01:10:02 INFO]: [LastLoginAPI] Downloaded library https://repo1.maven.org/maven2/org/ow2/asm/asm/7.1/asm-7.1.jar
[01:10:02 INFO]: [LastLoginAPI] Downloaded library https://repo1.maven.org/maven2/me/lucko/jar-relocator/1.4/jar-relocator-1.4.jar
[01:10:02 INFO]: [LastLoginAPI] Relocations applied to lib/org/reflections/reflections/0.9.12/reflections-0.9.12.jar
[01:10:02 INFO]: [LastLoginAPI] Downloaded library https://repo1.maven.org/maven2/org/jdbi/jdbi3-core/3.18.0/jdbi3-core-3.18.0.jar
[01:10:03 INFO]: [LastLoginAPI] Relocations applied to lib/org/jdbi/jdbi3-core/3.18.0/jdbi3-core-3.18.0.jar
[01:10:03 INFO]: [LastLoginAPI] Downloaded library https://repo1.maven.org/maven2/org/jdbi/jdbi3-stringtemplate4/3.18.0/jdbi3-stringtemplate4-3.18.0.jar
[01:10:03 INFO]: [LastLoginAPI] Relocations applied to lib/org/jdbi/jdbi3-stringtemplate4/3.18.0/jdbi3-stringtemplate4-3.18.0.jar
[01:10:03 INFO]: [LastLoginAPI] Downloaded library https://repo1.maven.org/maven2/org/antlr/ST4/4.3.1/ST4-4.3.1.jar
[01:10:03 INFO]: [LastLoginAPI] Relocations applied to lib/org/antlr/ST4/4.3.1/ST4-4.3.1.jar
[01:10:03 INFO]: [LastLoginAPI] Downloaded library https://repo1.maven.org/maven2/org/jdbi/jdbi3-sqlobject/3.18.0/jdbi3-sqlobject-3.18.0.jar
[01:10:03 INFO]: [LastLoginAPI] Relocations applied to lib/org/jdbi/jdbi3-sqlobject/3.18.0/jdbi3-sqlobject-3.18.0.jar
[01:10:03 INFO]: [LastLoginAPI] Downloaded library https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar
[01:10:03 INFO]: [LastLoginAPI] Relocations applied to lib/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar
[01:10:03 INFO]: [LastLoginAPI] Downloaded library https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.30/slf4j-simple-1.7.30.jar
[01:10:03 INFO]: [LastLoginAPI] Relocations applied to lib/org/slf4j/slf4j-simple/1.7.30/slf4j-simple-1.7.30.jar
[01:10:03 INFO]: [LastLoginAPI] Downloaded library https://repo1.maven.org/maven2/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar
[01:10:03 INFO]: [LastLoginAPI] Relocations applied to lib/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar
[01:10:03 INFO]: [LastLoginAPI] Downloaded library https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2.jar
[01:10:03 INFO]: [LastLoginAPI] Relocations applied to lib/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2.jar
[01:10:03 INFO]: [LastLoginAPI] Downloaded library https://repo1.maven.org/maven2/com/github/ben-manes/caffeine/caffeine/2.8.0/caffeine-2.8.0.jar
[01:10:04 INFO]: [LastLoginAPI] Relocations applied to lib/com/github/ben-manes/caffeine/caffeine/2.8.0/caffeine-2.8.0.jar
[01:10:04 INFO]: [LastLoginAPI] Downloaded library https://repo1.maven.org/maven2/io/leangen/geantyref/geantyref/1.3.7/geantyref-1.3.7.jar
[01:10:04 INFO]: [LastLoginAPI] Relocations applied to lib/io/leangen/geantyref/geantyref/1.3.7/geantyref-1.3.7.jar
[01:10:04 INFO]: [LastLoginAPI] Downloaded library https://repo1.maven.org/maven2/com/h2database/h2/1.4.200/h2-1.4.200.jar
[01:10:06 INFO]: Disconnecting Player: Server is still starting! Please wait before reconnecting.
[01:10:08 INFO]: Disconnecting Player: Server is still starting! Please wait before reconnecting.
[01:10:09 INFO]: [PlaceholderAPI] Successfully registered expansion: lastloginapi
[01:10:09 INFO]: [LastLoginAPI] Hooked into PlaceholderAPI
[01:10:09 INFO]: [LastLoginAPI] LastLoginAPI v1.5.1 enabled
```
</details>

**Comment by Agrrox** [comment]
```
[01:15:36 WARN]: [LastLoginAPI] Failed to parse format date
[01:15:36 WARN]: java.lang.IllegalArgumentException: Unknown pattern letter: l
[01:15:36 WARN]:        at java.time.format.DateTimeFormatterBuilder.parsePattern(DateTimeFormatterBuilder.java:1672)
[01:15:36 WARN]:        at java.time.format.DateTimeFormatterBuilder.appendPattern(DateTimeFormatterBuilder.java:1581)
[01:15:36 WARN]:        at java.time.format.DateTimeFormatter.ofPattern(DateTimeFormatter.java:536)
[01:15:36 WARN]:        at com.alessiodp.lastloginapi.common.utils.MessageUtils.formatDate(MessageUtils.java:58)
[01:15:36 WARN]:        at com.alessiodp.lastloginapi.common.addons.internal.LLPlaceholder.formatPlaceholder(LLPlaceholder.java:55)
[01:15:36 WARN]:        at com.alessiodp.lastloginapi.bukkit.addons.external.hooks.PAPIHook.onRequest(PAPIHook.java:73)
[01:15:36 WARN]:        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:156)
[01:15:36 WARN]:        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:69)
[01:15:36 WARN]:        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:97)
[01:15:36 WARN]:        at xyz.jpenilla.announcerplus.shaded.xyz.jpenilla.jmplib.compatability.JMPLibPAPIHook.translate(JMPLibPAPIHook.java:9)
[01:15:36 WARN]:        at xyz.jpenilla.announcerplus.shaded.xyz.jpenilla.jmplib.Chat.papiParse(Chat.java:44)
[01:15:36 WARN]:        at xyz.jpenilla.announcerplus.shaded.xyz.jpenilla.jmplib.Chat.parse(Chat.java:226)
[01:15:36 WARN]:        at xyz.jpenilla.announcerplus.config.ConfigManager.parse(ConfigManager.kt:173)
[01:15:36 WARN]:        at xyz.jpenilla.announcerplus.config.ConfigManager.parse(ConfigManager.kt:182)
[01:15:36 WARN]:        at xyz.jpenilla.announcerplus.config.JoinQuitConfig.onJoin(JoinQuitConfig.kt:160)
[01:15:36 WARN]:        at xyz.jpenilla.announcerplus.JoinQuitListener.onJoin(JoinQuitListener.kt:34)
[01:15:36 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor240.execute(Unknown Source)
[01:15:36 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61)
[01:15:36 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[01:15:36 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
[01:15:36 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[01:15:36 WARN]:        at net.minecraft.server.management.PlayerList.playerLoggedIn(PlayerList.java:469)
[01:15:36 WARN]:        at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:243)
[01:15:36 WARN]:        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:259)
[01:15:36 WARN]:        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:70)
[01:15:36 WARN]:        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:204)
[01:15:36 WARN]:        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:298)
[01:15:36 WARN]:        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:196)
[01:15:36 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:928)
[01:15:36 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467)
[01:15:36 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
[01:15:36 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630)
[01:15:36 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by AlessioDP** [comment]
I close the issue ;)

About these warnings, they are telling you that the config.yml is outdated. You can delete it and reload the plugin to automatically generate the new one, otherwise you can manually update it by looking the one in this repository :)

**Comment by AlessioDP** [comment]
The second error is related to a wrong format date, it must be correct and casual text must be between `'`.
