### ISSUE TITLE
Java 16 issue

### ISSUE THREAD

**Issue by BillyDas** [AlessioDP/LastLoginAPI#36]
Running paper 1.16.5
Last login API 1.5.1

Running into an error which disables the plugin, it could be Java 16's new syntax or some crap

```[13:48:21 ERROR]: Error occurred while enabling LastLoginAPI v1.5.1 (Is it up to date?)
java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @7177d78d
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
	at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
	at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
	at com.alessiodp.lastloginapi.core.common.addons.external.libby.classloader.URLClassLoaderHelper.<init>(URLClassLoaderHelper.java:42) ~[?:?]
	at com.alessiodp.lastloginapi.core.common.addons.external.libby.BukkitLibraryManager.<init>(BukkitLibraryManager.java:28) ~[?:?]
	at com.alessiodp.lastloginapi.core.bukkit.bootstrap.ADPBukkitBootstrap.onEnable(ADPBukkitBootstrap.java:33) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-776]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-776]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-776]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-776]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-776]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[13:48:21 INFO]: Disabling LastLoginAPI v1.5.1
[13:48:21 INFO]: [LastLoginAPI] Disabling LastLoginAPI
[13:48:21 ERROR]: Error occurred while disabling LastLoginAPI v1.5.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.alessiodp.lastloginapi.core.common.scheduling.ADPScheduler.shutdown()" because "this.scheduler" is null
	at com.alessiodp.lastloginapi.core.common.ADPPlugin.disabling(ADPPlugin.java:86) ~[?:?]
	at com.alessiodp.lastloginapi.core.bukkit.bootstrap.ADPBukkitBootstrap.onDisable(ADPBukkitBootstrap.java:39) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Paper-776]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.16.5.jar:git-Paper-776]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.16.5.jar:git-Paper-776]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.16.5.jar:git-Paper-776]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-776]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-776]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-776]
	at java.lang.Thread.run(Thread.java:831) [?:?]```

**Comment by AlessioDP** [comment]
Java 16 is not supported yet. Due to impossibility to load external libraries, I will work on it to find a way to make it work ;)
