### ISSUE TITLE
Password cannot start with "@"

### ISSUE THREAD

**Issue by Weasel-Beans** [AlessioDP/LastLoginAPI#67]
The plugin does not load the configuration if the mysql password begins with '@':

```
[22:13:26 INFO]: [LastLoginAPI] Initializing LastLoginAPI v1.7.3
[22:13:27 ERROR]: [LastLoginAPI] Failed to load configuration
com.alessiodp.lastloginapi.core.common.addons.external.simpleyaml.exceptions.InvalidConfigurationException: while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
 in 'string', line 81, column 17:
          password: @[redacted]
                    ^
        at com.alessiodp.lastloginapi.core.common.addons.external.simpleyaml.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:126) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.simpleyaml.configuration.file.YamlFile.loadFromString(YamlFile.java:242) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.simpleyaml.configuration.file.FileConfiguration.load(FileConfiguration.java:183) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.simpleyaml.configuration.file.FileConfiguration.load(FileConfiguration.java:154) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.simpleyaml.configuration.file.FileConfiguration.load(FileConfiguration.java:129) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.simpleyaml.configuration.file.YamlFile.load(YamlFile.java:219) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.simpleyaml.configuration.file.YamlFile.loadWithComments(YamlFile.java:237) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.configuration.ConfigurationFile.initializeConfiguration(ConfigurationFile.java:113) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.configuration.ConfigurationManager.reload(ConfigurationManager.java:28) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.common.LastLoginPlugin.loadCore(LastLoginPlugin.java:56) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.bukkit.BukkitLastLoginPlugin.loadCore(BukkitLastLoginPlugin.java:44) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.ADPPlugin.handle(ADPPlugin.java:188) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.ADPPlugin.enabling(ADPPlugin.java:88) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.bukkit.bootstrap.ADPBukkitBootstrap.onEnable(ADPBukkitBootstrap.java:38) ~[LastLoginAPI-1.7.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:667) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:318) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1166) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:318) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
 in 'string', line 81, column 17:
          password: @[redacted]
                    ^
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:460) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:251) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:660) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:166) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:214) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:184) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeKeyNode(Composer.java:310) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:301) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:491) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:416) ~[snakeyaml-1.30.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.simpleyaml.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:124) ~[LastLoginAPI-1.7.3.jar:?]
        ... 24 more
[22:13:27 ERROR]: [LastLoginAPI] Failed to load configuration
com.alessiodp.lastloginapi.core.common.addons.external.simpleyaml.exceptions.InvalidConfigurationException: while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
 in 'string', line 81, column 17:
          password: @[redacted]
                    ^
        at com.alessiodp.lastloginapi.core.common.addons.external.simpleyaml.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:126) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.simpleyaml.configuration.file.YamlFile.loadFromString(YamlFile.java:242) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.simpleyaml.configuration.file.FileConfiguration.load(FileConfiguration.java:183) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.simpleyaml.configuration.file.FileConfiguration.load(FileConfiguration.java:154) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.simpleyaml.configuration.file.FileConfiguration.load(FileConfiguration.java:129) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.simpleyaml.configuration.file.YamlFile.load(YamlFile.java:219) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.simpleyaml.configuration.file.YamlFile.loadWithComments(YamlFile.java:237) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.configuration.ConfigurationFile.loadConfigOptions(ConfigurationFile.java:161) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.common.configuration.data.ConfigMain.loadConfiguration(ConfigMain.java:139) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.configuration.ConfigurationManager.reload(ConfigurationManager.java:32) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.common.LastLoginPlugin.loadCore(LastLoginPlugin.java:56) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.bukkit.BukkitLastLoginPlugin.loadCore(BukkitLastLoginPlugin.java:44) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.ADPPlugin.handle(ADPPlugin.java:188) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.ADPPlugin.enabling(ADPPlugin.java:88) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.bukkit.bootstrap.ADPBukkitBootstrap.onEnable(ADPBukkitBootstrap.java:38) ~[LastLoginAPI-1.7.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:667) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:318) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1166) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:318) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
 in 'string', line 81, column 17:
          password: @[redacted]
                    ^
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:460) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:251) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:660) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:166) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:214) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:184) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeKeyNode(Composer.java:310) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:301) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:491) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:416) ~[snakeyaml-1.30.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.simpleyaml.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:124) ~[LastLoginAPI-1.7.3.jar:?]
        ... 25 more
[22:13:32 WARN]: [LastLoginAPI] The file config.yml is outdated!
```

Also, it seems to think the config file is outdated, despite the fact that it was generated on the latest version. This happened after I turned on the auto-update-config setting.

**Comment by AlessioDP** [comment]
Did you try to put the password into quotes?
```yaml
database: database
username: username
password: '@yourpassword'
```

**Comment by Weasel-Beans** [comment]
I did not try that, however that seems to solve the problem from what I can tell. Thanks
