### ISSUE TITLE
Failed to initialize library manager

### ISSUE THREAD

**Issue by otakurisu** [AlessioDP/LastLoginAPI#68]
Minecraft version: purpur-1.19-1708

The LastLoginAPI couldn't load properly when I started the server

```
[13:14:56 ERROR]: [LastLoginAPI] Failed to initialize library manager
java.lang.NullPointerException: Cannot invoke "Object.toString()" because "args[i]" is null
        at com.alessiodp.lastloginapi.core.common.libraries.LibraryLogger.log(LibraryLogger.java:22) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.slimjar.logging.MediatingProcessLogger.log(MediatingProcessLogger.java:39) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.slimjar.downloader.verify.ChecksumDependencyVerifier.prepareChecksumFile(ChecksumDependencyVerifier.java:100) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.slimjar.downloader.verify.ChecksumDependencyVerifier.verify(ChecksumDependencyVerifier.java:69) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.slimjar.downloader.URLDependencyDownloader.download(URLDependencyDownloader.java:71) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.slimjar.injector.helper.InjectionHelper.fetch(InjectionHelper.java:45) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.slimjar.injector.SimpleDependencyInjector.injectDependencies(SimpleDependencyInjector.java:58) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.slimjar.injector.SimpleDependencyInjector.injectDependencies(SimpleDependencyInjector.java:63) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.slimjar.injector.SimpleDependencyInjector.inject(SimpleDependencyInjector.java:52) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.slimjar.app.builder.InjectingApplicationBuilder.buildApplication(InjectingApplicationBuilder.java:63) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.slimjar.app.builder.ApplicationBuilder.build(ApplicationBuilder.java:462) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.slimjar.relocation.facade.ReflectiveJarRelocatorFacadeFactory.create(ReflectiveJarRelocatorFacadeFactory.java:128) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.slimjar.relocation.facade.ReflectiveJarRelocatorFacadeFactory.create(ReflectiveJarRelocatorFacadeFactory.java:118) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.slimjar.app.builder.ApplicationBuilder.getRelocatorFactory(ApplicationBuilder.java:335) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.slimjar.app.builder.ApplicationBuilder.createInjector(ApplicationBuilder.java:445) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.slimjar.app.builder.InjectingApplicationBuilder.buildApplication(InjectingApplicationBuilder.java:58) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.addons.external.slimjar.app.builder.ApplicationBuilder.build(ApplicationBuilder.java:462) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.libraries.LibraryManager.init(LibraryManager.java:40) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.common.ADPPlugin.loading(ADPPlugin.java:65) ~[LastLoginAPI-1.7.3.jar:?]
        at com.alessiodp.lastloginapi.core.bukkit.bootstrap.ADPBukkitBootstrap.onLoad(ADPBukkitBootstrap.java:33) ~[LastLoginAPI-1.7.3.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:458) ~[purpur-1.19.jar:git-Purpur-1708]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[purpur-1.19.jar:git-Purpur-1708]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1137) ~[purpur-1.19.jar:git-Purpur-1708]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1708]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:14:56 ERROR]: [LastLoginAPI] Failed to load libraries, the plugin will be stopped
```

**Comment by AlessioDP** [comment]
I will fix this null pointer issue but I tested it with a plain Purpur server and it works out of the box. Something happened when downloading external libraries.
